### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bguzryanto**
Hi dodekeract,

I discover a typo. Please check some small change I made.

Thank you

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
Thanks!

**Comment by FlorianWendelborn** [comment]
By the way, your git is not well-configured, so your profile doesn't get deteced by github and your commit doesn't get connected to your account. You should set the proper email address in your git config or tell github which emails to associate.

**Comment by bguzryanto** [comment]
ah, It describe why I need to clone using HTTPS instead of SSH. I think this is because I use new computer to commit the change and did not add my ssh key for the new computer, thank you for the reminder! :+1:

**Comment by bguzryanto** [comment]
@dodekeract I fixed the commit author, how do I apply to merged PR?

**Comment by FlorianWendelborn** [comment]
No idea.

**Comment by bguzryanto** [comment]
alright, thanks :)

**Pull request merged**
