### PR TITLE
added win/menu button codes

### PR DESCRIPTION
**Pull request by crimsonvspurple**
to default and rz layouts

### CODE REVIEW

**Comment by crimsonvspurple** [comment]
#62

**Comment by FlorianWendelborn** [comment]
I don't really know how this happened, but could you try to exclude the `settings-gameplay.jsx` file from the pull request? AFAIK it's the same as the version in the repo, but somehow it causes merge conflicts.

**Comment by crimsonvspurple** [comment]
I have no idea either why this happened. I tried to exclude it but it wont let me. I cant even revert these.

Do you think I should just fork again?

**Comment by FlorianWendelborn** [comment]
I guess that would be the easiest fix, however this may also be a good opportunity to learn about merging in git.

As far as I understand you have to pull all changes from my master branch to yours, merge them there and then send a pull request to mine, so that I can merge your changes.

**Comment by crimsonvspurple** [comment]
That's why I did though.

**Pull request closed without merging**
