### PR TITLE
added win/menu button

### PR DESCRIPTION
**Pull request by crimsonvspurple**

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
Thanks, I'm assuming you re-forked it?

**Comment by crimsonvspurple** [comment]
Yes.

The issue was...for some reason when i was trying to sync my fork, it didn't go thru/took a long time/something messed up. When I made the commit, it included a change that was already pushed to your master branch. The git gui client on windows is terrible.

**Comment by FlorianWendelborn** [comment]
Yeah, it's quite good for basic stuff though. When I was still using Windows and only worked on my own projects without any merge conflicts it was great.

**Comment by crimsonvspurple** [comment]
Hopefully with MS working on to bring more Linux stuff to Windows will motivate more people to improve on these fields.

**Pull request merged**
