### PR TITLE
Fixed action item layout issue

### PR DESCRIPTION
**Pull request by crimsonvspurple**

### CODE REVIEW

**Comment by crimsonvspurple** [comment]
#54

**Comment by dodekeract** [comment]
Fix #54.

**Comment by FlorianWendelborn** [comment]
Whoops

**Comment by FlorianWendelborn** [comment]
Live and working, thanks. Will publish to `npm` soon.

EDIT: Actually, I'll update `npm` later since my server doesn't have my npm credentials. :cry:

**Pull request merged**
